#!/usr/bin/env python3
"""
s438_oddclass_cp.py -- PRE-REGISTERED: the separatrix / complete-periodicity census
run on the ODD direction class, which no census in this repo has ever touched.

WHAT IS NEW, AND WHY IT IS EXACTLY THE [NCYL-059] BLIND SPOT.  [NCYL-059] reads "at
odd `P` the perpendicular direction is COMPLETELY PERIODIC -- 84/84 rows, Q <= 20".
Its instrument is `s276_separatrix_census.run_row`, whose direction grid is
`th = k*pi/Q` for `k in range(2*Q)` -- the EVEN absolute direction index `u = 2k` in
the `u*pi/(2Q)` labelling.  By [NCYL-240] the `4Q` launch angles carry exactly TWO
direction classes (`u` even / `u` odd), each an independently complete decomposition
of the same surface, and by [NCYL-112] the parity is CONSERVED.  So [NCYL-059]'s
`84/84` is a statement about ONE of the two classes, and the other has never been
asked the question at all.

WHY IT IS A SINGLE DIRECTION PER CLASS (and hence why the census is exhaustive).
All `2Q` grid directions of one parity are ONE direction on the surface -- holonomy
is generated by `pi` and `2alpha`, hence by `pi/Q` ([NCYL-018]) -- so enumerating the
inward grid directions of a fixed parity from BOTH cone points enumerates the
separatrices of a single surface direction, which is precisely what
`s276_separatrix_census.run_row` already does for the even class.  Tracing all of
them and asking only whether each ARRIVES at a cone point leaves no cylinder able to
hide ([NCYL-001]); no sampled measure can achieve that.

THE ONE-LINE GENERALISATION.  `inward_dirs` scans `k in range(2*Q)` at `k*pi/Q`;
here it scans `u in range(4*Q)` at `u*pi/(2*Q)` and filters on `u % 2`.  Setting
`parity=0` recovers the original grid exactly (`u = 2k`), which is CONTROL C1.
Nothing else in the geometry changes: `verts`/`reflect_velocity`/the arrival test are
parity-agnostic by construction, exactly as s315's docstring records for its own
odd-`P` extension.

HYPOTHESES (pre-registered).
  H1  CONTROL, RUN FIRST, ABLE TO FAIL.  At `parity=0` this probe reproduces
      `s276_separatrix_census.run_row` on its five rows -- identical
      `n_separatrices`, identical `n_closed`, identical arrival vertices -- and
      reproduces `s315_oddP_census`'s COMPLETE/MIXED classification on its rows.
      If H1 fails the refinement broke the tracer and nothing below is readable.
  H2  THE COUNT CONTROL, and it is an INDEPENDENT derivation, not a re-read.  The
      geometric enumeration (float `atan2` window tests) must equal an EXACT INTEGER
      count: the inward window at `O` is `u in (0, P)` and at `A` is
      `u in (2Q+P, 3Q)`, both OPEN, in units of `pi/(2Q)`.  Counting integers of a
      given parity in an open integer interval is exact arithmetic and shares no code
      with the float enumeration.  ** A mismatch means the window derivation is wrong
      and the census is not exhaustive -- it is a STOP condition, not a warning. **
      (s315's analogue caught a wrong closed-form guess at 3/7; this is that check
      re-derived per class rather than re-used, because s315's `ceil(Q/2)-1` is the
      EVEN-class count and has no reason to hold on the odd one.)
  H3  THE MEASUREMENT.  Per centre, per class: COMPLETELY PERIODIC / MIXED /
      UNRESOLVED, the closed fraction, and the arrival-margin distribution.  No
      prediction is pre-registered for the odd class -- it is the measurement.
  H4  THE SPLIT THAT MOTIVATED THE RUN (queue item (b)).  `8/15` is `P` even, so
      `L1` is its LONE side and [NCYL-018]'s minimal component sits in the LONE
      class; [NCYL-059]'s `84/84` is all odd `P`, i.e. all PAIRED classes.  The one
      known CP FAILURE and the big CP census are on OPPOSITE sides of the
      lone/paired split and the crossing cases have never been run.  Both classes
      are run at every centre here, so the crossing cases are in the table.

  ⚠ NOT pre-registered as expected-to-fail: [OPS-044] bars the self-applied
  named-wrong-hypothesis device.  The scoring discipline is [OPS-041] -- for each
  reported number, could it have come out otherwise?  H1 and H2 both can.

  ⚠ CAP DISCIPLINE ([OPS-201]).  `s315_cylinder_count`'s `CAP = 20000` is a
  PAIRED-class calibration and is off by more than an order of magnitude on the lone
  class (`7/16` closed `40/40` only at `200000`, word lengths to `77962`).  That
  ruling is about the CYLINDER enumerator, not this tracer, but the lesson transfers:
  a `reason='cap'` row is UNRESOLVED and is reported as such, never folded into
  MIXED.  The bounce cap here is inherited from `s276` (`2e7`) and every capped row
  is listed separately with its closest approach.

  ⚠ [NCYL-006]/[NCYL-008]: a finite trace can never establish a "never".  A row is
  reported COMPLETELY PERIODIC only when every separatrix ARRIVES; MIXED means some
  separatrix ran to the cap with a closest approach well outside the tolerance band,
  and the ambiguous band is reported rather than resolved.

PRIOR ART: grepped 'complete periodicity', 'completely periodic', 'separatrix
census', 'odd class', 'direction class', 'parity class', 'NCYL-059', 'NCYL-001',
'NCYL-018', 'NCYL-144', 'minimal component', 'CP census' across rulings.md /
cf_width_laws.md / computational_findings.md / TOOLS.md / future_directions.md ->
  - [NCYL-059] (s315) IS the even-class census being generalised; its 84/84 and its
    `9/19` tolerance artefact are inherited context, not re-derived.
  - [NCYL-001] (s276) gives the exhaustiveness argument and the cone-point set
    ("the right angle is REGULAR"); consumed unchanged, and it is direction-agnostic.
  - [NCYL-018] gives "all 2Q directions are ONE direction on the surface", which is
    what makes a per-class census well posed; and it is the `8/15` minimal component
    that H4 is about.
  - [NCYL-144] makes complete periodicity a load-bearing HYPOTHESIS of the lone-side
    full-sweep law (97/97 on that reading) -- so an odd-class CP verdict is an input
    to that law's lone/paired bookkeeping, which is why H4 is worth the run.
  - [NCYL-240]/[NCYL-241] (s437) establish the two-class structure and the loneness
    split this probe indexes by.
  - No ruling anywhere states a CP verdict for a non-even direction class.

STORE, NOT A ONE-OFF TABLE (`CLAUDE.md` measurement discipline).  One JSON file per
centre under `data/s438_cp_store/`, written atomically via `os.replace`, so the sweep
is resumable and killing it costs at most the in-flight centre.  A per-centre stall
counter and a stop file (`data/s438_cp_store/STOP`) bound it, per the s355 daemon
pattern.  ⚠ This is a NEW level (centre x direction class), deliberately NOT a
`cell_store` field: `cell_store`'s `verify()` asserts ONE partition per centre with
`sum(width) == 1`, and its founding DO-NOT is exactly the cross-partition merge.
"""
import json
import math
import os
import sys
import time

from right_triangle_billiards import RightTriangleBilliard

CAP = 20_000_000
ARRIVE_TOL = 1e-9
LADDER = [1_000, 10_000, 100_000, 1_000_000, 5_000_000, 20_000_000]
STORE = os.environ.get("S438_STORE", "data/s438_cp_store")
STOP = os.path.join(STORE, "STOP")


# ---------------------------------------------------------------- geometry

def verts(P, Q):
    """Identical to s276_separatrix_census.verts -- O and A are the cone points,
    R (the right angle) is REGULAR and is never an arrival ([NCYL-001], G3)."""
    alpha = (P / Q) * (math.pi / 2)
    L = 1.0 / math.tan(alpha)
    return {"O": (0.0, 0.0), "A": (L, 1.0)}, {"R": (L, 0.0)}, L, alpha


def inward_dirs(P, Q, vname, L, parity):
    """Grid directions of the given PARITY strictly inside the cone at `vname`.

    Generalises s276's `k*pi/Q` (= parity 0) to `u*pi/(2Q)`.  At parity=0 the
    returned angles are exactly s276's, which is CONTROL C1."""
    if vname == "O":
        lo, hi = 0.0, math.atan2(1.0, L)                        # between L2 (+x) and H
    else:                                                        # A: between H and L1
        lo, hi = math.pi + math.atan2(1.0, L), 1.5 * math.pi
    out = []
    for u in range(4 * Q):
        if u % 2 != parity:
            continue
        th = (u * math.pi / (2 * Q)) % (2 * math.pi)
        if lo + 1e-12 < th < hi - 1e-12:
            out.append(u)
    return out


def inward_count_exact(P, Q, vname, parity):
    """H2: the SAME count by exact integer arithmetic, sharing no code with the float
    window test above.  In units of pi/(2Q) the open inward window is (0, P) at O and
    (2Q+P, 3Q) at A -- because lo = alpha = P*pi/(2Q) at O and lo = pi + alpha,
    hi = 3pi/2 at A.  Count integers of the given parity strictly inside."""
    a, b = (0, P) if vname == "O" else (2 * Q + P, 3 * Q)
    return sum(1 for u in range(a + 1, b) if u % 2 == parity)


# ---------------------------------------------------------------- tracer

def trace_separatrix(B, Q, v0, u0, cap, cone, reg, tol=ARRIVE_TOL):
    """Launch from cone point `v0` in grid direction `u0*pi/(2Q)`.  Byte-for-byte
    s276's tracer with the direction formula generalised."""
    px, py = cone[v0]
    th = u0 * math.pi / (2 * Q)
    vx, vy = math.cos(th), math.sin(th)
    near_R = 0
    best = (1e9, None, 0)
    for n in range(1, cap + 1):
        cand = B._candidate_times(px, py, vx, vy)
        if not cand:
            return {"arrived": None, "hits": n, "reason": "escaped",
                    "near_R": near_R, "best_miss": best[0]}
        t, side = min(cand, key=lambda z: z[0])
        px += t * vx
        py += t * vy
        for nm, (qx, qy) in cone.items():
            d = math.hypot(px - qx, py - qy)
            if d < best[0]:
                best = (d, nm, n)
            if d < tol:
                return {"arrived": nm, "hits": n, "reason": "saddle_connection",
                        "near_R": near_R, "best_miss": d}
        for _, (qx, qy) in reg.items():          # G3: R is regular, never an arrival
            if math.hypot(px - qx, py - qy) < tol:
                near_R += 1
        vx, vy = B.reflect_velocity(side, vx, vy)
    return {"arrived": None, "hits": cap, "reason": "cap", "near_R": near_R,
            "best_miss": best[0], "best_at": best[2]}


# ---------------------------------------------------------------- per class

def perp_parities(P, Q):
    """[NCYL-240]: u_L1 = 2Q, u_L2 = Q, u_H = 3Q+P, parities 0, Q%2, (P+Q)%2.
    Returns {parity: [side names]} -- the class holding TWO side normals is PAIRED,
    the one holding ONE is LONE ([NCYL-113]'s 2+1 split)."""
    d = {0: [], 1: []}
    d[0].append("L1")
    d[Q % 2].append("L2")
    d[(P + Q) % 2].append("H")
    return d


def run_class(P, Q, parity, cap=CAP):
    cone, reg, L, alpha = verts(P, Q)
    B = RightTriangleBilliard(alpha)
    recs, count_ok = [], True
    for v0 in ("O", "A"):
        dirs = inward_dirs(P, Q, v0, L, parity)
        if len(dirs) != inward_count_exact(P, Q, v0, parity):
            count_ok = False                    # H2 STOP condition
        for u0 in dirs:
            r = trace_separatrix(B, Q, v0, u0, cap, cone, reg)
            r.update({"from": v0, "u": u0})
            recs.append(r)
    closed = [r for r in recs if r["arrived"]]
    opens = [r for r in recs if not r["arrived"]]
    roles = perp_parities(P, Q)
    return {
        "P": P, "Q": Q, "parity": parity, "cap": cap,
        "class_role": "paired" if len(roles[parity]) == 2 else "lone",
        "perp_sides": "|".join(roles[parity]),
        "count_check_ok": count_ok,
        "n_separatrices": len(recs), "n_closed": len(closed),
        "frac_closed": len(closed) / max(1, len(recs)),
        "verdict": classify(recs, count_ok),
        "worst_miss_of_open": max([r["best_miss"] for r in opens], default=None),
        "min_miss_of_open": min([r["best_miss"] for r in opens], default=None),
        "n_capped": sum(1 for r in opens if r["reason"] == "cap"),
        "n_escaped": sum(1 for r in opens if r["reason"] == "escaped"),
        "near_R_total": sum(r["near_R"] for r in recs),
        "curve": [{"depth": d,
                   "n_closed": sum(1 for r in closed if r["hits"] <= d)}
                  for d in LADDER if d <= cap],
        "records": recs,
    }


def classify(recs, count_ok):
    if not count_ok:
        return "COUNT_MISMATCH"
    opens = [r for r in recs if not r["arrived"]]
    if not opens:
        return "COMPLETELY_PERIODIC"
    if any(r["reason"] == "escaped" for r in opens):
        return "ESCAPED"
    # [NCYL-059]'s band: a closest approach inside it is not resolvable at this tol.
    if any(6.2e-10 <= r["best_miss"] <= 1e-9 for r in opens):
        return "UNRESOLVED"
    return "MIXED"


# ---------------------------------------------------------------- store

def _path(P, Q):
    return os.path.join(STORE, f"{P}_{Q}.json")


def _write(rec):
    os.makedirs(STORE, exist_ok=True)
    tmp = _path(rec["P"], rec["Q"]) + ".tmp"
    with open(tmp, "w") as f:
        json.dump(rec, f)
    os.replace(tmp, _path(rec["P"], rec["Q"]))      # atomic: old record or new, never torn


def get(P, Q, cap=CAP, refresh=False):
    p = _path(P, Q)
    if not refresh and os.path.exists(p):
        try:
            rec = json.load(open(p))
            if rec.get("cap", 0) >= cap:
                return rec
        except (json.JSONDecodeError, OSError):
            pass
    t0 = time.time()
    classes = {str(par): run_class(P, Q, par, cap) for par in (0, 1)}
    rec = {"P": P, "Q": Q, "cap": cap, "secs": round(time.time() - t0, 1),
           "classes": classes}
    _write(rec)
    return rec


def summary(rec):
    out = []
    for par in ("0", "1"):
        c = rec["classes"][par]
        out.append(f"u%2={par} {c['class_role']:<6} [{c['perp_sides']:<5}] "
                   f"sep={c['n_separatrices']:<3} closed={c['n_closed']:<3} "
                   f"{c['verdict']}")
    return out


# ---------------------------------------------------------------- controls

def h1_control(verbose=True):
    """C1: at parity 0 this probe must reproduce s276_separatrix_census.run_row."""
    import s276_separatrix_census as s276
    ok = True
    for (P, Q, tag) in s276.ROWS:
        mine = run_class(P, Q, 0, cap=s276.CAP)
        theirs = s276.run_row(P, Q, cap=s276.CAP)
        same = (mine["n_separatrices"] == theirs["n_separatrices"]
                and mine["n_closed"] == theirs["n_closed"]
                and sorted(r["arrived"] or "-" for r in mine["records"])
                    == sorted(r["arrived"] or "-" for r in theirs["records"]))
        ok &= same
        if verbose:
            print(f"  H1 {P}/{Q:<3} {tag:<30} mine sep={mine['n_separatrices']} "
                  f"closed={mine['n_closed']} | s276 sep={theirs['n_separatrices']} "
                  f"closed={theirs['n_closed']}  {'OK' if same else '** MISMATCH **'}",
                  flush=True)
    return ok


def h2_control(Qmax=40, verbose=True):
    """C2: the float window enumeration vs the exact integer count, every centre,
    both parities, both vertices.  Shares no code with the enumeration."""
    bad = []
    for Q in range(3, Qmax + 1):
        for P in range(1, Q):
            if math.gcd(P, Q) != 1:
                continue
            _, _, L, _ = verts(P, Q)
            for par in (0, 1):
                for v in ("O", "A"):
                    g = len(inward_dirs(P, Q, v, L, par))
                    e = inward_count_exact(P, Q, v, par)
                    if g != e:
                        bad.append((P, Q, par, v, g, e))
    if verbose:
        print(f"  H2 exact-vs-geometric separatrix count: {len(bad)} mismatches "
              f"over Q<={Qmax}", flush=True)
        for b in bad[:10]:
            print(f"     {b[0]}/{b[1]} parity={b[2]} {b[3]}: geom={b[4]} exact={b[5]}",
                  flush=True)
    return not bad


# ---------------------------------------------------------------- sweep

def centres(Qmax, Qmin=3):
    out = []
    for Q in range(Qmin, Qmax + 1):
        for P in range(1, Q):
            if math.gcd(P, Q) == 1:
                out.append((P, Q))
    return out


def sweep(Qmax=24, deadline=None, cap=CAP, verbose=True):
    todo = centres(Qmax)
    done = stalled = 0
    for (P, Q) in todo:
        if os.path.exists(STOP):
            print(f"STOP file present -- halting after {done} centres", flush=True)
            break
        if deadline and time.time() > deadline:
            print(f"deadline reached -- halting after {done} centres", flush=True)
            break
        if os.path.exists(_path(P, Q)):
            continue
        try:
            rec = get(P, Q, cap=cap)
        except Exception as exc:                 # a bad centre must not kill the sweep
            stalled += 1
            print(f"{P}/{Q}: STALLED {type(exc).__name__}: {exc}", flush=True)
            continue
        done += 1
        if verbose:
            for line in summary(rec):
                print(f"{P:>3}/{Q:<3} {line}  [{rec['secs']}s]", flush=True)
    print(f"sweep done: {done} measured, {stalled} stalled, store={STORE}", flush=True)


def analyse(verbose=True):
    """Read the store and cross-tab.  ⚠ THREE THINGS THAT ARE NOT EVIDENCE, scored
    out explicitly ([OPS-041]):
      (i)  a class with ZERO separatrices is VACUOUSLY completely periodic and cannot
           fail -- counted separately and excluded from every rate;
      (ii) [NCYL-003] already records `4/21`, `10/23`, `20/23` as TRUNCATION OR
           BORDERLINE, not genuine plateaus, so a MIXED verdict on those rows is not
           new information -- flagged, not counted as a discovery;
      (iii) [NCYL-006]/[NCYL-008]: a finite trace cannot establish a "never", so a
           MIXED row is a CANDIDATE minimal component and the closest approach of its
           open separatrices is quoted so the reader can judge."""
    known_borderline = {(4, 21), (10, 23), (20, 23)}
    recs, rows = [], []
    for fn in sorted(os.listdir(STORE)):
        if not fn.endswith(".json"):
            continue
        recs.append(json.load(open(os.path.join(STORE, fn))))
    for r in recs:
        for par in ("0", "1"):
            c = r["classes"][par]
            rows.append(c)
    live = [c for c in rows if c["n_separatrices"] > 0]
    vac = [c for c in rows if c["n_separatrices"] == 0]
    tab = {}
    for c in live:
        tab[(c["class_role"], c["verdict"])] = tab.get(
            (c["class_role"], c["verdict"]), 0) + 1
    mixed = [c for c in live if c["verdict"] != "COMPLETELY_PERIODIC"]

    # [NCYL-059]'s claim re-read on THIS store: odd P, Q<=20, the EVEN class (which is
    # always the one holding L1, since u_L1 = 2Q).  A disagreement means one of the two
    # instruments is wrong; agreement is a cross-instrument control that could fail.
    n059 = [c for c in live if c["P"] % 2 == 1 and c["Q"] <= 20 and c["parity"] == 0]
    n059_bad = [c for c in n059 if c["verdict"] != "COMPLETELY_PERIODIC"]

    if verbose:
        print(f"centres={len(recs)}  class-rows={len(rows)}  "
              f"live={len(live)}  vacuous(sep=0, cannot fail)={len(vac)}", flush=True)
        for role in ("lone", "paired"):
            tot = sum(v for (rl, _), v in tab.items() if rl == role)
            cp = tab.get((role, "COMPLETELY_PERIODIC"), 0)
            print(f"  {role:<6}: {cp}/{tot} COMPLETELY PERIODIC", flush=True)
        print(f"  [NCYL-059] re-read (odd P, Q<=20, even class): "
              f"{len(n059) - len(n059_bad)}/{len(n059)} CP"
              f"{'  ** DISAGREES **' if n059_bad else '  (agrees)'}", flush=True)
        print("  non-CP rows:", flush=True)
        for c in sorted(mixed, key=lambda z: (z["Q"], z["P"])):
            flag = " [NCYL-003 borderline]" if (c["P"], c["Q"]) in known_borderline \
                else ""
            print(f"    {c['P']:>3}/{c['Q']:<3} {c['class_role']:<6} "
                  f"[{c['perp_sides']:<5}] {c['verdict']:<10} "
                  f"closed={c['n_closed']}/{c['n_separatrices']} "
                  f"min_miss_open={c['min_miss_of_open']:.3e} "
                  f"capped={c['n_capped']}{flag}", flush=True)
    return {"n_centres": len(recs), "n_live": len(live), "n_vacuous": len(vac),
            "table": {f"{k[0]}/{k[1]}": v for k, v in tab.items()},
            "ncyl059_rows": len(n059), "ncyl059_disagree": len(n059_bad),
            "non_cp": [{k: c[k] for k in
                        ("P", "Q", "parity", "class_role", "perp_sides", "verdict",
                         "n_closed", "n_separatrices", "min_miss_of_open",
                         "worst_miss_of_open", "n_capped")} for c in mixed]}


def main():
    args = sys.argv[1:]
    os.makedirs(STORE, exist_ok=True)
    if args and args[0] == "analyse":
        res = analyse()
        with open("data/s438_oddclass_cp_summary.json", "w") as f:
            json.dump(res, f, indent=1)
        print("wrote data/s438_oddclass_cp_summary.json", flush=True)
        sys.exit(0)
    if args and args[0] == "controls":
        print("CONTROLS (both able to fail; H2 is a STOP condition)", flush=True)
        ok2 = h2_control(Qmax=40)
        ok1 = h1_control()
        print(f"H1={'PASS' if ok1 else 'FAIL'}  H2={'PASS' if ok2 else 'FAIL'}",
              flush=True)
        sys.exit(0 if (ok1 and ok2) else 1)
    Qmax = int(args[0]) if args else 24
    hours = float(args[1]) if len(args) > 1 else 6.0
    sweep(Qmax=Qmax, deadline=time.time() + hours * 3600)


if __name__ == "__main__":
    main()
