"""Section 2 (and the field facts of Sections 3.1 and 3.3): the directions met, the phase
space, its area, and the field K.

Statements checked:
  * The group generated by the reflections theta -> pi - theta, -theta, 2 alpha - theta
    has rotation part (pi/15)Z, and the orbit of the horizontal direction is the 30
    directions k pi / 15 -- computed by closure, not quoted.
  * The phase space of the direction class is T0 x {theta_k}, of total measure
    2Q area(T0) = Q cot(alpha) = area(B) = 13.5060606644675...; area(T0) = 0.4502...
  * K = Q(zeta_30)^+ = Q(cos(pi/15)) has degree 4: the minimal polynomial of
    c = cos(pi/15) is 16x^4 + 8x^3 - 16x^2 - 8x + 1; cos(2pi/15) = 2c^2 - 1,
    cos(pi/5) = 4c^3 - 3c, and the change of basis from {1, c, c^2, c^3} to
    {1, cos(pi/15), cos(2pi/15), cos(pi/5)} is triangular with determinant 8.
  * cot(alpha) has minimal polynomial x^8 - 28x^6 + 134x^4 - 92x^2 + 1, of degree 8, so
    cot(alpha) is not in K (Section 3.3).
"""
from t0 import P, Q, KAPPA, check, done, trunc

import sympy as sp


def main():
    print('Section 2 -- directions, phase space, the field K\n')
    # the reflection group on directions, in units of pi/30, by closure
    gens = [lambda m: (30 - m) % 60, lambda m: (-m) % 60, lambda m: (2 * P - m) % 60]
    orbit, frontier = {30}, [30]
    while frontier:
        m = frontier.pop()
        for g in gens:
            n = g(m)
            if n not in orbit:
                orbit.add(n)
                frontier.append(n)
    check(f'orbit of the horizontal direction has {len(orbit)} elements (expect 2Q = 30)',
          len(orbit) == 2 * Q)
    check('it is exactly {k pi/15}', orbit == set(range(0, 60, 2)))
    # rotation part: products of two reflections are m -> m + (difference of constants)
    rot = {(a - b) % 60 for a in (30, 0, 2 * P) for b in (30, 0, 2 * P)}
    sub, frontier = {0}, [0]
    while frontier:
        r = frontier.pop()
        for g in rot:
            n = (r + g) % 60
            if n not in sub:
                sub.add(n)
                frontier.append(n)
    check('rotation part is (pi/15)Z', sub == set(range(0, 60, 2)))

    area_T0 = KAPPA / 2
    area_B = KAPPA * Q
    print(f'\n  area(T0)       = {trunc(area_T0.value(), 13)}')
    print(f'  area(B)        = {trunc(area_B.value(), 13)}')
    check('2Q area(T0) = Q cot(alpha) exactly', area_T0 * (2 * Q) == area_B)
    check('area(B) = 13.5060606644675...', trunc(area_B.value(), 13) == '13.5060606644675')
    check('area(T0) = 0.4502...', trunc(area_T0.value(), 4) == '0.4502')

    x = sp.symbols('x')
    c = sp.cos(sp.pi / 15)
    mp_c = sp.minimal_polynomial(c, x)
    check(f'minpoly(cos(pi/15)) = {sp.expand(mp_c)}',
          sp.expand(mp_c - (16 * x**4 + 8 * x**3 - 16 * x**2 - 8 * x + 1)) == 0)
    check('cos(2pi/15) = 2c^2 - 1', sp.simplify(sp.cos(2 * sp.pi / 15) - (2 * c**2 - 1)) == 0)
    check('cos(pi/5) = 4c^3 - 3c', sp.simplify(sp.cos(sp.pi / 5) - (4 * c**3 - 3 * c)) == 0)
    # columns: 1, c, 2c^2 - 1, 4c^3 - 3c in the power basis {1, c, c^2, c^3}
    Mchg = sp.Matrix([[1, 0, -1, 0], [0, 1, 0, -3], [0, 0, 2, 0], [0, 0, 0, 4]])
    check(f'change of basis is triangular with determinant {Mchg.det()} (expect 8)',
          Mchg.det() == 8 and Mchg.is_upper)
    mp_cot = sp.minimal_polynomial(sp.cot(4 * sp.pi / 15), x)
    check(f'minpoly(cot(4pi/15)) = {sp.expand(mp_cot)}, degree {sp.degree(mp_cot, x)}',
          sp.expand(mp_cot - (x**8 - 28 * x**6 + 134 * x**4 - 92 * x**2 + 1)) == 0)
    check('so cot(alpha) is not in K (degree 8 > 4)', sp.degree(mp_cot, x) == 8)
    done()


if __name__ == '__main__':
    main()
